### ISSUE TITLE
Versa 2 Fuzzy language Face 

### ISSUE THREAD

**Issue by Starsick** [asellitt/fuzzy-text-clockface#1]
Good day, your clock face with fuzzy natural language does not display all of the steps. It only shows 3 digits I need Caillou you, for example, if you go 8950 steps it only shows 895. This is on the Fitbit versa 2

**Comment by asellitt** [comment]
Thanks for the report! 

v1.2 (https://github.com/asellitt/fuzzy-text-clockface/releases/tag/1.2) has a fix for this issue.

I put it up for review last night, and as soon as FitBit approve it, it should be live. I'm hoping it will be available by the end of the week.

I'll report back once its live.

**Comment by asellitt** [comment]
The update had been approved and I've just published it. You should be able to update to v1.2 and no longer have this issue. 

Thanks again for the bug report.
